### ISSUE TITLE
CFBot - one or more methods isn't working

### ISSUE THREAD

**Issue by vedarad** [debmalya/allgo#1]
opponentMatching and shortestSolutionLength aren't valid solutions!

**Comment by Zikt** [comment]
There's a problem with plagiarismCheck.

Exception in thread "main" java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at myCode._invoke(file.java on line ?)
	at myCode.main(file.java on line ?)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at myCode._invoke(file.java on line ?)
	... 1 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1927)
	at _runyiovh.remove(file.java on line 26)
	at _runyiovh.plagiarismCheck(file.java on line 10)
	... 6 more
